package main

import (
	"fmt"
	"strings"
)

// FormatOutput enhances the LLM output with better formatting
func FormatOutput(analysis string, outputLevel string) string {
	var formatted strings.Builder

	// Add header based on output level
	switch outputLevel {
	case "executive":
		formatted.WriteString("📊 EXECUTIVE SUMMARY\n")
		formatted.WriteString(strings.Repeat("=", 70) + "\n\n")
	case "technical":
		formatted.WriteString("🔧 TECHNICAL ANALYSIS\n")
		formatted.WriteString(strings.Repeat("=", 70) + "\n\n")
	case "detailed":
		formatted.WriteString("📋 COMPREHENSIVE DESIGN ANALYSIS\n")
		formatted.WriteString(strings.Repeat("=", 70) + "\n\n")
	}

	// Add the analysis content
	formatted.WriteString(analysis)
	formatted.WriteString("\n\n")

	// Add footer with metadata
	formatted.WriteString(strings.Repeat("=", 70) + "\n")
	formatted.WriteString(fmt.Sprintf("Analysis Level: %s\n", strings.ToUpper(outputLevel)))
	formatted.WriteString("Generated by CAD/Design PDF Analysis Tool\n")
	formatted.WriteString(strings.Repeat("=", 70) + "\n")

	return formatted.String()
}

